"""
Common agents - LangGraph nodes shared across different review workflows.

Nodes for interview, pausing, and routing decisions:
- Human pause for interaction
- Interview node for user questions
- Router for conditional flow

Prompts are loaded from YAML files in prompts/common/.
"""

from ..state import ReviewState
from ..utils.llm_utils.llm_providers import get_llm
from ..utils.file_utils.helpers import fmt_chunks, fmt_snippets, summarize_hist, truncate
from ..utils.llm_utils.prompt_loader import load_prompt, get_prompt_field

# Constants (may need to be moved to config)
TERMINATION_PT = {"fim", "terminar", "sair", "encerrar", "pronto", "acabar"}
TERMINATION_EN = {"end", "finish", "exit", "done", "stop", "quit"}
TERMINATION = TERMINATION_PT | TERMINATION_EN


def human_pause_node(state: ReviewState) -> dict:
    """Human-in-the-loop pause node."""
    return {}


def interview_node(state: ReviewState) -> dict:
    """Generates a question for the user based on the current plan.
    
    Args:
        state (ReviewState): The current state of the review, expected to contain:
            - "theme": str, the review topic/theme.
            - "current_plan": str, the current plan generated by the agent.
            - "interview_history": list of (role, content) tuples representing the conversation history.
            - "questions_asked": int, number of questions asked so far.
            - "max_questions": int, maximum number of questions to ask before finalizing.
    
    Returns:
        dict: Updated state with the new question added to the interview history and incremented question count.
    """
    theme              = state["theme"]
    review_type        = state.get("review_type", "academic")
    questions_asked    = state["questions_asked"]
    max_questions      = state["max_questions"]
    current_plan       = truncate(state["current_plan"], 500)
    current_history    = summarize_hist(state["interview_history"], 1)
    remaining = max_questions - questions_asked

    if review_type in {"tecnico", "technical"}:
        ctx_extra  = fmt_snippets(state.get("technical_snippets", [])[-3:], 400)
        instructions = get_prompt_field("common/interview", "instructions_technical")
        type_label = "technical chapter"
    else:
        ctx_extra  = fmt_chunks(state.get("relevant_chunks", [])[-16:], 400)
        instructions = get_prompt_field("common/interview", "instructions_academic")
        type_label = "literature review"

    prompt = load_prompt(
        "common/interview",
        theme=repr(theme),
        type_label=type_label,
        current_plan=current_plan,
        current_history=current_history,
        ctx_extra=ctx_extra,
        question_num=questions_asked + 1,
        max_questions=max_questions,
        remaining=remaining,
        instructions=instructions,
    )
    ans     = get_llm(temperature=prompt.temperature).invoke(prompt.text)
    question = ans.content if hasattr(ans, "content") else str(ans)
    return {
        "interview_history": [("assistant", question)],
        "questions_asked": questions_asked + 1,
        "status": "waiting_user",
    }


def interview_router(state: ReviewState) -> str:
    """Decide whether to continue the interview or end it.
    
    Args:
        state (ReviewState): The current state of the review, expected to contain:
            - "questions_asked": int, number of questions asked so far.
            - "max_questions": int, maximum number of questions to ask before finalizing.
            - "interview_history": list of (role, content) tuples representing the conversation history.
    
    Returns:
        str: "finish" if the interview should end, "continue" otherwise.
    """
    if state.get("questions_asked", 0) >= state.get("max_questions", 3):
        return "finish"
    for role, c in reversed(state.get("interview_history", [])):
        if role == "user":
            if set(c.lower().strip().split()) & TERMINATION:
                return "finish"
            break
    return "continue"

