"""
Common agents - LangGraph nodes shared across different review workflows.

Nodes for interview, pausing, and routing decisions:
- Human pause for interaction
- Interview node for user questions
- Router for conditional flow

Prompts are loaded from YAML files in prompts/common/.
"""

import mlflow

from ..state import ReviewState
from ..utils.file_utils.helpers import (
    fmt_chunks,
    fmt_snippets,
    summarize_hist,
    truncate,
)
from ..utils.llm_utils.llm_providers import get_llm
from ..utils.llm_utils.prompt_loader import get_prompt_field, load_prompt

# Constants (may need to be moved to config)
TERMINATION_PT = {"fim", "terminar", "sair", "encerrar", "pronto", "acabar"}
TERMINATION_EN = {"end", "finish", "exit", "done", "stop", "quit"}
TERMINATION = TERMINATION_PT | TERMINATION_EN


def build_search_query(state: ReviewState) -> str:
    """Builds a focused search query from the latest interview Q&A pair via LLM.

    Walks the ``interview_history`` in reverse to locate the most recent
    assistant question and user response.  When found, invokes the
    ``common/refine_search_query`` prompt to generate a concise query string.
    Falls back to the raw ``theme`` when no Q&A pair exists or when the LLM
    call fails.

    Args:
        state (ReviewState): The current graph state, expected to contain:
            - "theme": str, the review topic used as fallback query.
            - "interview_history": list of ``(role, content)`` tuples.
            - "current_plan": str, the latest draft plan (used as context).

    Returns:
        str: A concise search query string (3–8 words).

    Raises:
        None: All exceptions from ``load_prompt`` or the LLM call are caught
            internally; the function always returns a usable string.
    """
    theme = state["theme"]
    current_plan = state.get("current_plan", "")

    last_question = ""
    user_response = ""

    history = state.get("interview_history", [])
    for i in range(len(history) - 1, -1, -1):
        entry = history[i]
        if not (isinstance(entry, list | tuple) and len(entry) == 2):
            continue
        role, msg = entry
        if role == "user" and not user_response:
            user_response = msg
        elif role == "assistant" and user_response and not last_question:
            last_question = msg
            break

    if last_question and user_response:
        try:
            prompt = load_prompt(
                "common/refine_search_query",
                theme=theme,
                current_plan=truncate(current_plan, 500),
                last_question=truncate(last_question, 400),
                user_response=truncate(user_response, 400),
            )
            resp = get_llm(temperature=prompt.temperature).invoke(prompt.text)
            raw = resp.content if hasattr(resp, "content") else str(resp)
            query = next(
                (line.strip().strip('"').strip("'") for line in raw.splitlines() if line.strip()),
                theme,
            )
            return query or theme
        except Exception:
            return theme

    return theme


def human_pause_node(state: ReviewState) -> dict:
    """Human-in-the-loop pause node."""
    return {}


@mlflow.trace(name="interview", span_type="AGENT")
def interview_node(state: ReviewState) -> dict:
    """Generates a question for the user based on the current plan.

    Args:
        state (ReviewState): The current state of the review, expected to contain:
            - "theme": str, the review topic/theme.
            - "current_plan": str, the current plan generated by the agent.
            - "interview_history": list of (role, content) tuples representing the conversation history.
            - "questions_asked": int, number of questions asked so far.
            - "max_questions": int, maximum number of questions to ask before finalizing.

    Returns:
        dict: Updated state with the new question added to the interview history and incremented question count.
    """
    theme = state["theme"]
    review_type = state.get("review_type", "academico")
    questions_asked = state["questions_asked"]
    max_questions = state["max_questions"]
    current_plan = truncate(state["current_plan"], 500)
    current_history = summarize_hist(state["interview_history"], 1)
    remaining = max_questions - questions_asked

    if review_type in {"tecnico", "technical"}:
        ctx_extra = fmt_snippets(state.get("technical_snippets", [])[-3:], 400)
        instructions = get_prompt_field("common/interview", "instructions_technical")
        type_label = "technical chapter"
    else:
        ctx_extra = fmt_chunks(state.get("relevant_chunks", [])[-16:], 400)
        instructions = get_prompt_field("common/interview", "instructions_academic")
        type_label = "literature review"

    prompt = load_prompt(
        "common/interview",
        theme=repr(theme),
        type_label=type_label,
        current_plan=current_plan,
        current_history=current_history,
        ctx_extra=ctx_extra,
        question_num=questions_asked + 1,
        max_questions=max_questions,
        remaining=remaining,
        instructions=instructions,
    )
    ans = get_llm(temperature=prompt.temperature).invoke(prompt.text)
    question = ans.content if hasattr(ans, "content") else str(ans)
    return {
        "interview_history": [("assistant", question)],
        "questions_asked": questions_asked + 1,
        "status": "waiting_user",
    }


def interview_router(state: ReviewState) -> str:
    """Decide whether to continue the interview or end it.

    Args:
        state (ReviewState): The current state of the review, expected to contain:
            - "questions_asked": int, number of questions asked so far.
            - "max_questions": int, maximum number of questions to ask before finalizing.
            - "interview_history": list of (role, content) tuples representing the conversation history.

    Returns:
        str: "finish" if the interview should end, "continue" otherwise.
    """
    if state.get("questions_asked", 0) >= state.get("max_questions", 3):
        return "finish"
    for role, c in reversed(state.get("interview_history", [])):
        if role == "user":
            if set(c.lower().strip().split()) & TERMINATION:
                return "finish"
            break
    return "continue"


@mlflow.trace(name="identify_and_refine", span_type="AGENT")
def identify_and_refine_node(state: ReviewState) -> dict:
    """Detect language and evaluate vagueness before any search starts.

    When the theme is vague or the language cannot be determined, extracts the
    USER_MESSAGE from the LLM response and appends it to ``interview_history``
    so the Gradio handler surfaces it as a chat message without any UI changes.

    If the latest ``interview_history`` entry is a user reply to a previous
    refinement question, the user's answer is used as the candidate theme for
    re-evaluation.

    Args:
        state (ReviewState): The current graph state, expected to contain:
            - "theme": str, the original review topic.
            - "interview_history": list of (role, content) tuples.

    Returns:
        dict: Partial state update with the following keys:

            - ``theme`` (str): The candidate theme, possibly updated from the
              user's last reply.
            - ``detected_language`` (str): ``"PT"``, ``"EN"``, or ``"UNKNOWN"``.
            - ``is_theme_vague`` (bool): Whether the LLM flagged the theme as
              too broad.
            - ``is_theme_refined`` (bool): ``True`` when language is known and
              theme is specific; triggers downstream search.
            - ``refinement_feedback`` (list[str]): Single-element list with the
              raw LLM response. **Replaces** the previous value in the state
              (plain ``list[str]`` reducer — last write wins).
            - ``interview_history`` (list[tuple]): Single-element list with the
              ``("assistant", <message>)`` tuple to display to the user.
              **Appended** to the existing history via the
              ``operator.add`` reducer defined on the field.
    """
    import re

    original_theme = state.get("theme", "")

    # If the user replied to a previous refinement question where the theme
    # itself was vague (is_theme_vague=True), treat the reply as the candidate
    # theme. When only the language was unknown we keep the original theme —
    # the reply is a language choice, not a new topic.
    candidate_theme = original_theme
    was_vague = state.get("is_theme_vague", False)
    history = state.get("interview_history", [])
    if was_vague and history:
        last_role, last_content = history[-1]
        if last_role == "user" and last_content.strip():
            candidate_theme = last_content.strip()

    prompt = load_prompt("common/refine_theme", theme=candidate_theme)
    ans = get_llm(temperature=prompt.temperature).invoke(prompt.text)
    content = ans.content if hasattr(ans, "content") else str(ans)

    is_vague = bool(
        re.search(r"^IS THE THEME VAGUE\?\s*YES", content, re.IGNORECASE | re.MULTILINE)
    )

    lang_match = re.search(
        r"^DETECTED LANGUAGE:\s*(PT|EN|UNKNOWN)", content, re.IGNORECASE | re.MULTILINE
    )
    detected_lang = lang_match.group(1).upper() if lang_match else "UNKNOWN"

    language_unknown = detected_lang == "UNKNOWN"
    needs_clarification = is_vague or language_unknown

    # Extract the USER_MESSAGE block; stop at the next all-caps heading or end of string.
    # The inline flag (?i:...) scopes IGNORECASE only to the prefix match, so the
    # heading terminator [A-Z][A-Z_ ]+: remains case-sensitive and does not
    # prematurely cut off message text that contains "Word: ..." sentences.
    user_msg_match = re.search(
        r"(?i:USER_MESSAGE:)\s*\n([\s\S]+?)(?:\n[A-Z][A-Z_ ]+:|\.?\Z)",
        content,
    )
    if user_msg_match:
        user_message = user_msg_match.group(1).strip()
    elif is_vague and language_unknown:
        user_message = (
            f'⚠️ Your theme "{candidate_theme}" seems too broad and I couldn\'t detect the language. '
            "Could you provide a more specific topic or research question? "
            "Also, please let me know if you'd like to proceed in English (EN) or Portuguese (PT)."
        )
    elif language_unknown:
        user_message = (
            f'I couldn\'t determine the language for the theme "{candidate_theme}". '
            "Would you like to proceed in English (EN) or Portuguese (PT)?"
        )
    elif is_vague and detected_lang == "PT":
        user_message = (
            f'⚠️ O tema "{candidate_theme}" parece muito amplo para uma revisão focada. '
            "Você poderia fornecer um tópico mais específico ou uma pergunta de pesquisa?"
        )
    elif is_vague and detected_lang == "EN":
        user_message = (
            f'⚠️ Your theme "{candidate_theme}" seems too broad for a focused review. '
            "Could you provide a more specific topic or research question?"
        )
    else:
        if detected_lang == "PT":
            user_message = f'✅ Tema entendido ({detected_lang}). Iniciando a revisão para: "{candidate_theme}". Um momento...'
        else:
            user_message = (
                f'✅ Theme understood ({detected_lang}). Proceeding with: "{candidate_theme}".'
            )

    return {
        "theme": candidate_theme,
        "detected_language": detected_lang,
        "is_theme_vague": is_vague,
        "is_theme_refined": not needs_clarification,
        "refinement_feedback": [content],
        "interview_history": [("assistant", user_message)],
    }


def refinement_router(state: ReviewState) -> str:
    """Route after identify_and_refine: proceed to search or pause for user clarification.

    Args:
        state: The current graph state, expected to contain:
            - "is_theme_refined": bool, True when theme is specific and language is known.

    Returns:
        str: "proceed" if theme is ready, "clarify" if user input is needed.
    """
    if state.get("is_theme_refined", False):
        return "proceed"
    return "clarify"


def post_pause_router(state: ReviewState) -> str:
    """Route after human_pause: re-evaluate theme or proceed to plan interview.

    If the theme has been refined, proceed to search. If still unrefined, loop
    back to identify_and_refine so the node can re-evaluate the user's latest
    answer. If a plan already exists, we are in the normal interview loop.

    Args:
        state: The current graph state, expected to contain:
            - "is_theme_refined": bool
            - "current_plan": str, empty until the first plan is generated.

    Returns:
        str: One of three routing values:

            - ``"interview"``: A plan already exists, so the user is in the
              normal plan-refinement interview loop.
            - ``"re_evaluate"``: No plan yet and theme still needs
              clarification — loops back to ``identify_and_refine``.
            - ``"proceed"``: Safety-net branch. Reached only when no plan
              exists *and* ``is_theme_refined`` is already ``True`` (e.g.
              the theme was accepted on the first attempt and the pause was
              triggered by an unrelated event). Skips re-evaluation and
              moves directly to the search phase.
    """
    if state.get("current_plan", ""):
        return "interview"
    if state.get("is_theme_refined", False):
        return "proceed"
    return "re_evaluate"
