# Pacote revisao_agent
from .workflows.academic_workflow import build_academico_workflow
from .workflows.technical_workflow import build_tecnico_workflow
from .workflows.technical_writing_workflow import build_escrita_tecnica_workflow